# Generated by Django 3.0.3 on 2020-02-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photos',
            field=models.ImageField(null=True, upload_to='screenshots'),
        ),
    ]
